# Generated by Django 6.0.3 on 2026-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="содержимое")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="превью")),
                ("publication_attribute", models.BooleanField(default=True, verbose_name="опубликовано")),
                ("count_views", models.IntegerField(default=0, verbose_name="просмотры")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["created_at", "count_views"],
            },
        ),
    ]
