# Generated by Django 6.0.3 on 2026-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_count_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.IntegerField(default=0, editable=False, verbose_name="просмотры"),
        ),
    ]
