# Generated by Django 6.0.3 on 2026-04-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_count_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at", "-count_views"],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
