# Generated by Django 6.0.3 on 2026-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="изображение"),
        ),
    ]
